spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minierp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
    mode: HTML
    encoding: UTF-8

server:
  port: 8080

jwt:
  secret: your-secret-key
  expiration: 3600000
